name: PR Verify

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  merge_group:
  push:
    branches: [ main ]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prlint:
    permissions: write-all
    name: PR convention & autolabel
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.4.1
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          custom_labels: '{"feat": "feature", "docs": "documentation", "ci": "CI/CD"}'
          add_scope_label: true